# Generated by Django 3.1.3 on 2020-12-01 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.UserManage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('sex', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=0)),
                ('head_pic', models.CharField(max_length=100)),
                ('from_type', models.IntegerField(default=0)),
                ('phone_num', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('wechat', models.CharField(max_length=50)),
                ('class_num', models.IntegerField(default=0)),
                ('grade_num', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=1)),
                ('phone_num_state', models.IntegerField(default=0)),
                ('email_state', models.IntegerField(default=0)),
                ('wechat_state', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(verbose_name='date created')),
                ('birth_time', models.DateTimeField(verbose_name='birthday')),
                ('last_login', models.DateTimeField(verbose_name='last login time')),
                ('is_deleted', models.IntegerField(default=0)),
                ('delete_time', models.DateTimeField(verbose_name='delete time')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', main.UserManage.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TbDorm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('build_num', models.IntegerField(unique=True)),
                ('num_beds', models.IntegerField(default=4)),
                ('num_empty', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TbLegalCauseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cause', models.CharField(max_length=3000)),
                ('result', models.CharField(max_length=50)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TbRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('state', models.IntegerField(default=1)),
                ('comment', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrUserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField(default=1)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tbrole')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrUserDorm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField(default=1)),
                ('dorm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tbdorm')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tbuser',
            name='dorm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tbdorm'),
        ),
        migrations.AddField(
            model_name='tbuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='tbuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
